language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.1
  - ruby-head

gemfile:
  - gemfiles/Gemfile.rails-3.0
  - gemfiles/Gemfile.rails-3.1
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.2
  - gemfiles/Gemfile.rails-edge

sudo: false

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-4.0
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-4.1
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-4.2
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.2.1
      gemfile: gemfiles/Gemfile.rails-3.0
    - rvm: 2.2.1
      gemfile: gemfiles/Gemfile.rails-3.1
    - rvm: 2.2.1
      gemfile: gemfiles/Gemfile.rails-3.2
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-3.0
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-3.1
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-3.2
  allow_failures:
    - rvm: ruby-head
