language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.2
  - ruby-head

gemfile:
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.2

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
